spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/tripplanner
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop